apiVersion: 1
datasources:
  - name: FleetTruth Prometheus
    type: prometheus
    uid: fleettruth-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
